name = "swag-platform-api"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[vars]
APP_ENV = "production"
APP_NAME = "Swag Platform"
API_VERSION = "v1"

[[env.staging.vars]]
APP_ENV = "staging"

[[env.dev.vars]]
APP_ENV = "development"
